$(document).ready(function(){
	$('.slider').slick({
		arrows:true,
		dots:true,
		adaptiveHeight:true,
		slidesToShow:1,
		speed:1000,
		easing:'linear',
		autoplay:true,
		autoplaySpeed:400,
	});
});